package com.bannerbound.antiquity.client.ponder.scenes;

import net.createmod.ponder.api.scene.SceneBuilder;
import net.createmod.ponder.api.scene.SceneBuildingUtil;
import net.minecraft.core.Direction;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ItemStack;
import net.neoforged.api.distmarker.Dist;
import net.neoforged.api.distmarker.OnlyIn;

/**
 * Shared helpers for the Bannerbound: Antiquity ponder storyboards. Every station scene animates
 * over the same blank 5x5x5 platform NBT (checkerboard floor at y=0, air above) generated by
 * {@code PonderNbtGen}; stations are built on top of that floor at runtime via
 * {@code scene.world().setBlock(...)}, so a scene needs no station-specific structure file -
 * only the matching {@code ponder/<sceneName>.nbt} platform copy. PLATE is the 5-wide footprint
 * passed to configureBasePlate; CX/CZ is the centre column single-block stations sit on and CY
 * (y=1) is the floor's top face. basePlate is the standard scene opener (plate + zoom + reveal):
 * critically, showBasePlate() only reveals the y=0 floor layer while Ponder's setBlock merely
 * redraws already-shown sections and never reveals new cells, so basePlate also shows the y>=1
 * layers up front - the cells are air, so the reveal is invisible - otherwise every
 * programmatically placed block lands in a hidden section and renders as nothing (the "no
 * blocks" bug). itemNbt builds minimal 1.21.1 ItemStack NBT (id + count, components default
 * to empty).
 */
@OnlyIn(Dist.CLIENT)
public final class PonderUtil {
    private PonderUtil() {}

    public static final int PLATE = 5;
    public static final int CX = 2, CZ = 2;
    public static final int CY = 1;

    public static void basePlate(SceneBuilder scene, SceneBuildingUtil util, float scale) {
        scene.configureBasePlate(0, 0, PLATE);
        scene.scaleSceneView(scale);
        scene.showBasePlate();
        // Must reveal y>=1 up front: setBlock never reveals hidden sections ("no blocks" bug).
        scene.world().showSection(util.select().layersFrom(1), Direction.DOWN);
        scene.idle(5);
    }

    public static ItemStack stack(String id) {
        Item item = BuiltInRegistries.ITEM.get(ResourceLocation.parse(id));
        return new ItemStack(item);
    }

    public static ItemStack stack(String id, int count) {
        ItemStack s = stack(id);
        s.setCount(count);
        return s;
    }

    public static CompoundTag itemNbt(String id, int count) {
        CompoundTag t = new CompoundTag();
        t.putString("id", id);
        t.putInt("count", count);
        return t;
    }
}
